/* The London Academy - CEFR question bank
   Original questions written for this lead-capture test.
   Structure: level, question, options, correct, topic, explanation.
*/
window.QUESTIONS = [
  // A1
  {level:'A1', topic:'present simple', question:'Choose the correct sentence.', options:['She live in Parma.','She lives in Parma.','She living in Parma.','She is live in Parma.'], correct:1, explanation:'Con he/she/it al Present Simple aggiungiamo -s: she lives.'},
  {level:'A1', topic:'be verb', question:'Complete the sentence: I ___ from Italy.', options:['am','is','are','be'], correct:0, explanation:'Con I usiamo am: I am from Italy.'},
  {level:'A1', topic:'questions', question:'Choose the correct question.', options:['Where you live?','Where do you live?','Where does you live?','Where are you live?'], correct:1, explanation:'Con you al Present Simple usiamo do: Where do you live?'},
  {level:'A1', topic:'articles', question:'Complete: I have ___ English lesson today.', options:['a','an','the','-'], correct:1, explanation:'English inizia con suono vocalico, quindi usiamo an.'},
  {level:'A1', topic:'possessives', question:'Complete: This is Marco. ___ car is red.', options:['Her','His','Their','Your'], correct:1, explanation:'Marco è maschile: his car.'},
  {level:'A1', topic:'daily routine', question:'Complete: I usually ___ breakfast at 7:30.', options:['have','has','having','am have'], correct:0, explanation:'Con I usiamo have: I usually have breakfast.'},
  {level:'A1', topic:'prepositions', question:'Complete: The meeting is ___ Monday.', options:['in','on','at','to'], correct:1, explanation:'Con i giorni della settimana usiamo on.'},
  {level:'A1', topic:'there is/are', question:'Complete: There ___ two cafés near the station.', options:['is','are','be','am'], correct:1, explanation:'Two cafés è plurale, quindi there are.'},
  {level:'A1', topic:'can', question:'Choose the correct sentence.', options:['I can to speak English.','I can speaking English.','I can speak English.','I can speaks English.'], correct:2, explanation:'Dopo can usiamo il verbo base: can speak.'},
  {level:'A1', topic:'numbers and prices', question:'You hear: “It costs fifteen euros.” What is the price?', options:['5 euros','15 euros','50 euros','51 euros'], correct:1, explanation:'Fifteen significa 15.'},
  {level:'A1', topic:'word order', question:'Choose the correct order.', options:['I coffee like.','Like I coffee.','I like coffee.','Coffee I like very.'], correct:2, explanation:'In inglese l’ordine base è soggetto + verbo + oggetto.'},
  {level:'A1', topic:'negative forms', question:'Complete: I ___ like tea.', options:['not','no','don’t','doesn’t'], correct:2, explanation:'Con I al Present Simple negativo usiamo don’t.'},

  // A2
  {level:'A2', topic:'past simple', question:'Complete: Yesterday I ___ to Milan for work.', options:['go','went','gone','was go'], correct:1, explanation:'Il Past Simple di go è went.'},
  {level:'A2', topic:'future plans', question:'Complete: We ___ visit London next month.', options:['are going to','going','go to','are go to'], correct:0, explanation:'Per intenzioni future usiamo be going to.'},
  {level:'A2', topic:'comparatives', question:'Complete: Parma is ___ than Rome.', options:['small','smaller','more small','the smallest'], correct:1, explanation:'Con aggettivi brevi usiamo -er: smaller than.'},
  {level:'A2', topic:'countable/uncountable', question:'Complete: I need ___ information about the course.', options:['an','some','many','a few'], correct:1, explanation:'Information è uncountable: some information.'},
  {level:'A2', topic:'requests', question:'Choose the most natural request in a hotel.', options:['Give me room.','Can I have a room, please?','I want room now.','Room for me.'], correct:1, explanation:'Can I have..., please? è una richiesta semplice e cortese.'},
  {level:'A2', topic:'present perfect intro', question:'Complete: I ___ never been to Dublin.', options:['have','has','did','am'], correct:0, explanation:'Con I usiamo have + past participle.'},
  {level:'A2', topic:'past continuous', question:'Complete: I called you, but you ___ driving.', options:['was','were','are','did'], correct:1, explanation:'Con you usiamo were: you were driving.'},
  {level:'A2', topic:'modal verbs', question:'Complete: You ___ show your passport at the airport.', options:['must','can to','must to','should to'], correct:0, explanation:'Must è seguito dal verbo base senza to.'},
  {level:'A2', topic:'reading', question:'A sign says: “Please keep your ticket until the end of your journey.” What should you do?', options:['Throw the ticket away immediately.','Keep the ticket while you travel.','Buy a ticket at the end.','Give the ticket to another passenger.'], correct:1, explanation:'Until the end significa fino alla fine del viaggio.'},
  {level:'A2', topic:'prepositions', question:'Complete: We arrived ___ the airport at 8 pm.', options:['to','in','at','on'], correct:2, explanation:'Con airport come luogo specifico usiamo at.'},
  {level:'A2', topic:'adverbs', question:'Choose the correct sentence.', options:['He drives careful.','He drives carefully.','He carefully drives always.','He drive carefully.'], correct:1, explanation:'Per descrivere il verbo drive usiamo l’avverbio carefully.'},
  {level:'A2', topic:'conditionals basic', question:'Complete: If it rains, we ___ at home.', options:['stay','will stay','stayed','staying'], correct:1, explanation:'Nel First Conditional: if + present, will + verbo base.'},

  // B1
  {level:'B1', topic:'present perfect vs past simple', question:'Choose the correct sentence.', options:['I have seen him yesterday.','I saw him yesterday.','I see him yesterday.','I was seen him yesterday.'], correct:1, explanation:'Con un tempo finito come yesterday usiamo Past Simple.'},
  {level:'B1', topic:'conditionals', question:'Complete: If I had more time, I ___ English every day.', options:['study','will study','would study','studied'], correct:2, explanation:'Second Conditional: if + past simple, would + verbo base.'},
  {level:'B1', topic:'phrasal verbs', question:'Complete: Could you ___ the form before the lesson?', options:['fill in','fill up','fill on','fill over'], correct:0, explanation:'Fill in a form significa compilare un modulo.'},
  {level:'B1', topic:'reported speech', question:'Direct: “I am busy.” Reported: She said she ___ busy.', options:['is','was','has been','will be'], correct:1, explanation:'Nel reported speech spesso il tempo arretra: am diventa was.'},
  {level:'B1', topic:'passive voice', question:'Complete: English ___ in many countries.', options:['speaks','is spoken','is speaking','has spoken'], correct:1, explanation:'Forma passiva: be + past participle = is spoken.'},
  {level:'B1', topic:'travel vocabulary', question:'At the airport, what does “boarding pass” mean?', options:['A document that lets you enter the plane.','A place where you collect luggage.','A person who checks passports.','A fee for extra luggage.'], correct:0, explanation:'Il boarding pass è il documento per salire sull’aereo.'},
  {level:'B1', topic:'linkers', question:'Complete: ___ it was raining, we went for a walk.', options:['Because','Although','So','Despite of'], correct:1, explanation:'Although introduce un contrasto: anche se pioveva.'},
  {level:'B1', topic:'modal deduction', question:'Complete: He has worked all day. He ___ be tired.', options:['can’t','must','mustn’t','would'], correct:1, explanation:'Must indica deduzione forte: deve essere stanco.'},
  {level:'B1', topic:'word formation', question:'Complete: This course is very ___.', options:['use','useful','usefully','using'], correct:1, explanation:'Serve un aggettivo: useful.'},
  {level:'B1', topic:'relative clauses', question:'Complete: This is the teacher ___ helped me prepare for the exam.', options:['which','where','who','whose'], correct:2, explanation:'Per persone usiamo who.'},
  {level:'B1', topic:'email language', question:'Choose the best phrase to end a semi-formal email.', options:['Bye mate','Best regards','See ya','Kisses'], correct:1, explanation:'Best regards è adatto a email semi-formali.'},
  {level:'B1', topic:'listening meaning', question:'If someone says “I’m running late”, they mean:', options:['They are jogging.','They will arrive late.','They are leaving early.','They are very fast.'], correct:1, explanation:'Running late significa essere in ritardo.'},

  // B2
  {level:'B2', topic:'advanced vocabulary', question:'Complete: The new policy will have a significant ___ on small businesses.', options:['impact','collision','touch','hit'], correct:0, explanation:'Have an impact on è una collocazione naturale.'},
  {level:'B2', topic:'mixed conditionals', question:'Complete: If I had studied harder, I ___ more confident now.', options:['am','will be','would be','would have been'], correct:2, explanation:'Mixed conditional: past condition, present result = would be.'},
  {level:'B2', topic:'passive reporting', question:'Choose the best sentence.', options:['It is said that the exam is difficult.','It says that the exam difficult.','It is say the exam is difficult.','It said that difficult exam.'], correct:0, explanation:'Forma impersonale passiva: It is said that...'},
  {level:'B2', topic:'collocations', question:'Complete: We need to ___ a decision by Friday.', options:['do','make','take on','build'], correct:1, explanation:'In inglese si dice make a decision.'},
  {level:'B2', topic:'subtle meaning', question:'“The proposal is unlikely to be accepted.” This means:', options:['It will certainly be accepted.','It probably will not be accepted.','It has already been accepted.','Nobody understands it.'], correct:1, explanation:'Unlikely significa improbabile.'},
  {level:'B2', topic:'formal English', question:'Choose the most formal option.', options:['I want to know prices.','Can you tell me prices?','I would like to enquire about your prices.','Tell me the prices now.'], correct:2, explanation:'I would like to enquire about... è più formale e professionale.'},
  {level:'B2', topic:'gerund/infinitive', question:'Complete: I look forward to ___ from you.', options:['hear','hearing','to hear','heard'], correct:1, explanation:'Look forward to richiede gerundio: hearing.'},
  {level:'B2', topic:'articles', question:'Complete: ___ rich should contribute fairly to society.', options:['A','The','An','-'], correct:1, explanation:'The + aggettivo può indicare una categoria di persone: the rich.'},
  {level:'B2', topic:'inversion', question:'Choose the correct sentence.', options:['Rarely I have seen such progress.','Rarely have I seen such progress.','Rarely I seen such progress.','Rarely have seen I such progress.'], correct:1, explanation:'Con avverbi negativi/limitativi iniziali si usa inversione: Rarely have I...'},
  {level:'B2', topic:'reading inference', question:'A review says: “The course is demanding but rewarding.” What does it imply?', options:['It is easy and useless.','It requires effort but gives good results.','It is boring and short.','It is only for children.'], correct:1, explanation:'Demanding = impegnativo; rewarding = gratificante/utile.'},
  {level:'B2', topic:'business English', question:'Complete: We need to ___ the deadline because the client is waiting.', options:['meet','arrive','touch','catch'], correct:0, explanation:'Meet a deadline significa rispettare una scadenza.'},
  {level:'B2', topic:'pronoun reference', question:'In “The teacher gave Anna her book”, whose book is it most likely?', options:['The teacher’s or Anna’s; context is unclear.','Only the teacher’s.','Only Anna’s.','Nobody’s.'], correct:0, explanation:'La frase è ambigua senza contesto: her può riferirsi a teacher o Anna.'},

  // C1
  {level:'C1', topic:'nuance', question:'Choose the sentence with the closest meaning to: “He fell short of expectations.”', options:['He exceeded expectations.','He did not meet expectations.','He had no expectations.','He refused expectations.'], correct:1, explanation:'Fall short of expectations significa non essere all’altezza delle aspettative.'},
  {level:'C1', topic:'advanced collocation', question:'Complete: The company managed to ___ a compromise after long negotiations.', options:['reach','arrive','touch','get in'], correct:0, explanation:'Reach a compromise è la collocazione corretta.'},
  {level:'C1', topic:'concession', question:'Choose the best phrase: ___ the risks, the project was approved.', options:['Although','Despite','In spite that','Even'], correct:1, explanation:'Despite + noun phrase: despite the risks.'},
  {level:'C1', topic:'cleft sentence', question:'Choose the correct emphasis structure.', options:['What I need is more practice.','What I need it is more practice.','That I need is more practice.','What need I is more practice.'], correct:0, explanation:'Cleft sentence corretta: What I need is...'},
  {level:'C1', topic:'formal style', question:'Choose the most precise formal sentence.', options:['We looked at the problem.','We conducted an in-depth analysis of the issue.','We saw the thing.','We checked stuff.'], correct:1, explanation:'Conducted an in-depth analysis è più preciso e formale.'},
  {level:'C1', topic:'idiom', question:'If a plan is “a long shot”, it is:', options:['very likely to succeed','unlikely but possible','already finished','too short'], correct:1, explanation:'A long shot indica qualcosa di poco probabile ma possibile.'},
  {level:'C1', topic:'hedging', question:'Choose the sentence that sounds appropriately cautious in academic/business English.', options:['This proves everything.','This may suggest a possible trend.','This is 100% true forever.','This kills all debate.'], correct:1, explanation:'May suggest a possible trend usa hedging, cioè linguaggio prudente.'},
  {level:'C1', topic:'advanced grammar', question:'Complete: Had I known about the delay, I ___ earlier.', options:['would leave','would have left','will leave','left'], correct:1, explanation:'Inversione del third conditional: Had I known..., I would have left.'},
  {level:'C1', topic:'register', question:'Which phrase is too informal for a professional email?', options:['Please find attached','I would appreciate your feedback','Cheers, mate','Kind regards'], correct:2, explanation:'Cheers, mate è troppo informale per molte email professionali.'},
  {level:'C1', topic:'lexical precision', question:'Complete: The results were ___ with previous research.', options:['consistent','constant','consequent','considerate'], correct:0, explanation:'Consistent with significa coerente con.'},

  // C2
  {level:'C2', topic:'idiomatic nuance', question:'“The argument does not hold water.” This means:', options:['It is convincing.','It is not logically sound.','It is about water.','It is very emotional.'], correct:1, explanation:'Does not hold water significa che un’argomentazione non regge.'},
  {level:'C2', topic:'high-level vocabulary', question:'Complete: The speaker’s explanation was clear, but somewhat ___.', options:['oversimplified','overdoneful','simpled','clearful'], correct:0, explanation:'Oversimplified significa eccessivamente semplificata.'},
  {level:'C2', topic:'subtle contrast', question:'Choose the best completion: The policy is not illegal; ___, it raises ethical concerns.', options:['nevertheless','therefore','because','unless'], correct:0, explanation:'Nevertheless introduce un contrasto rispetto alla prima frase.'},
  {level:'C2', topic:'advanced style', question:'Choose the most natural sentence.', options:['The data are indicative of a broader shift.','The data is indicate of a broader shift.','The data indicates of a broader shift.','The data are indication to a broad shift.'], correct:0, explanation:'Be indicative of è una struttura avanzata e naturale.'},
  {level:'C2', topic:'pragmatics', question:'If someone says “That’s one way of looking at it”, they may be:', options:['fully agreeing','politely expressing doubt','asking for directions','ending a phone call'], correct:1, explanation:'Può essere un modo indiretto e cortese per non essere pienamente d’accordo.'},
  {level:'C2', topic:'collocation', question:'Complete: The report provides ___ insight into consumer behaviour.', options:['valuable','valued','valueless','valuably'], correct:0, explanation:'Valuable insight è una collocazione naturale.'},
  {level:'C2', topic:'inference', question:'A manager says: “We may need to revisit the timeline.” What is implied?', options:['The timeline is definitely perfect.','The timeline may need to be changed.','The project is cancelled.','The timeline is unknown.'], correct:1, explanation:'Revisit the timeline significa rivedere/scadenzare nuovamente il piano.'},
  {level:'C2', topic:'register and diplomacy', question:'Choose the most diplomatic disagreement.', options:['You are wrong.','That makes no sense.','I see your point, though I would interpret the data differently.','No, absolutely not.'], correct:2, explanation:'La terza opzione è ferma ma diplomatica e professionale.'},
  {level:'C2', topic:'complex grammar', question:'Complete: No sooner had we launched the campaign ___ the first leads arrived.', options:['when','than','that','then'], correct:1, explanation:'Struttura fissa: No sooner... than.'},
  {level:'C2', topic:'precision', question:'Complete: The issue was not resolved, but it was ___ mitigated.', options:['substantially','substance','substantial','substantiate'], correct:0, explanation:'Serve un avverbio: substantially mitigated.'}
];
